---
- name: Deploy webapp on tomcat
  hosts: webservers
  become: true
  tasks:
  - name: Delete webapp diretory
    ansible.builtin.file:
      path: /opt/tomcat8/webapps/project-devops
      state: absent
  - name: Dete .war file
    ansible.builtin.file:
      path: /opt/tomcat8/webapps/project-devops.war
      state: absent
  - name: Copy .war file from master to destination
    ansible.builtin.copy:
      src: target/project-devops.war
      dest: /opt/tomcat8/webapps/project-devops.war 
